image: node:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

testing_testing:
  stage: test
  script: npm test

deploy:
  image: python:latest
  stage: deploy
  script:
    - rm -rf /var/lib/apt/lists/*
    - apt-get update
    - apt-cache gencaches
    - apt-get install -y zip unzip
    - echo HOST=$HOST >> .env
    - echo USERNAME=$USERNAME >> .env
    - echo PASSWORD=$PASSWORD >> .env
    - echo DATABASE=$DATABASE >> .env
    - ls -sail
    - zip test.zip -r .
    - pip install awscli
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region us-east-2
    - aws s3 cp test.zip s3://elasticbeanstalk-us-east-2-669867583814/test-$CI_PIPELINE_ID.zip 
    - aws elasticbeanstalk create-application-version --application-name dna-mutation-GitLab-CI --version-label test-$CI_PIPELINE_ID.zip --source-bundle S3Bucket=elasticbeanstalk-us-east-2-669867583814,S3Key=test-$CI_PIPELINE_ID.zip
    - aws elasticbeanstalk update-environment --application-name dna-mutation-GitLab-CI --environment-name  DnaMutationGitlabCi-env --version-label test-$CI_PIPELINE_ID.zip
